# Generated by Django 5.2.6 on 2025-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
