# Generated by Django 5.2.6 on 2025-10-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L,XL', help_text='Các size có sẵn, ngăn cách bởi dấu phẩy', max_length=50),
        ),
    ]
