# Generated by Django 5.2.6 on 2025-10-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_available_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Size S'), ('M', 'Size M'), ('L', 'Size L'), ('XL', 'Size XL')], max_length=5)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Tổng số lượng trong kho')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Số lượng đang giữ trong giỏ hàng')),
                ('sold_quantity', models.IntegerField(default=0, help_text='Số lượng đã bán')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.product')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'ordering': ['product', 'size'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
