# Generated by Django 5.2.6 on 2025-10-18 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Giảm theo phần trăm (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(default=0, help_text='Giảm theo số tiền (VNĐ)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
