# Generated by Django 5.2.6 on 2025-10-19 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, help_text='Users đã sử dụng mã này', related_name='used_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
