# Generated by Django 5.2.6 on 2025-10-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_coupon_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Size S'), ('M', 'Size M'), ('L', 'Size L'), ('XL', 'Size XL')], default='M', max_length=5),
        ),
    ]
