# Generated by Django 5.2.6 on 2025-10-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_birth_date_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_street',
            field=models.CharField(blank=True, max_length=300, verbose_name='Số nhà, đường'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã'),
        ),
    ]
