# Generated by Django 5.2.6 on 2025-10-19 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_address_city_profile_address_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_ward',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255, verbose_name='Số nhà, tên đường')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
